### ISSUE TITLE
Modded hostile mobs still spawn

### ISSUE THREAD

**Issue by DraTrav** [GeheimagentNr1/MagicalTorches#1]
**Versions**
Minecraft Version: 1.19.2
Minecraft Forge Version: 43.2.13
Mod Version: 2.0.2

**Describe the bug**
Mob torches not blocking modded hostile mobs

**To Reproduce**
Steps to reproduce the behaviour:
1. Place mega torch
2. notice any modded mob still spawns

**Expected behaviour**
all hostile mobs stop spawning

**Additional context**
Modded mobs such as mobs from mekanism or earth mobs mods. They can be added to the list however this does not follow what the default behavior claims

┆Issue is synchronized with this [Trello card](https://trello.com/c/UfkneV9v) by [Unito](https://www.unito.io)

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Fixed</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>2.0.3</td></tr><tr><th>Fix release date:</th><td>12.08.23</td></tr></tbody></table>

**TODOs:**

*   [x] Fix issue

**Comment by GeheimagentNr1** [comment]
The issue is fixed for Minecraft versions 1.19.2, 1.19.4 and 1.20.1.  
Fix is uploaded and under review.
